name = "newwebsitecfc"
main = "_worker.js"
compatibility_date = "2026-07-06"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "CUES_DATA"
id = "f227ff087f63414ab71061761e17ed7a"

[[secrets_store_secrets]]
binding = "ADMIN_PASSWORD"
store_id = "7b6edbfd782541a3b09550e1cbcf3373"
secret_name = "admin-password"

[[secrets_store_secrets]]
binding = "SESSION_SECRET"
store_id = "7b6edbfd782541a3b09550e1cbcf3373"
secret_name = "SESSION_SECRET"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
